language: php

services:
  - mysql

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - mysql -u root -e 'CREATE DATABASE test;'

script:
  - vendor/bin/phpunit -c tests.xml
